### ISSUE TITLE
Can you support connection to local S3 also?

### ISSUE THREAD

**Issue by djangofan** [huoqi/AWS-S3-Tool#1]
Can you support connection to local S3 also  (on Firefox Quantum)?

I can't connect to a local S3 with your tool.  Image registered like:
docker run -p 4569:4569 --name s3-local --restart unless-stopped -d lphoward/fake-s3

**Comment by huoqi** [comment]
Hi, Jon
I'm afraid that this tool supports some basic functions for S3. It use AWS SDK for Javascript. I am glad you can develop it to support connection to local S3. I think you can modify the endpoint of S3 to support it.
